

- hosts: nvr8
  tasks:
    # - name: blah testing
    #   debug: msg={{ znc_server_passwords.freenode }}
    #   tags:
    #     - debug
  roles: 
    # - common
    - dhellmann.znc-on-znc
  vars_files:
    - vars/passwords.yml
  vars:
    znc_system_user: znc
    znc_system_group: znc

    znc_user:
        name: anuvrat
        hash: e9059912a1029988d23521a5611b1618bdd3eafaab42042571696866458d05de
        salt: F,XlQrvHkV.7AteB1yh5
        method: sha256

    znc_nick: anuvrat
    znc_quit_msg: disconnecting
    znc_real_name: Anuvrat Parashar
    znc_networks:
      - name: freenode
        server_name: chat.freenode.net
        server_port: 6667
        ident: anuvrat
        channels:
          - "#openstack"
          - "#openstack-dev"
          - "#wsme"
          - "#python"
          - "#django"
          - "#pocoo"
          - "#pydelhi"
          - "#ansible"
          - "#docker"
          - "##linux-india"
          - "#dgplug"
          - "#asetalias"      
      # - name: tech404
      #   ident: anuvrat
      #   server_name: tech404.irc.slack.com
      #   server_port: "+6697"
      #   channels:
      #     - "#python"
      #     - "#openstack"
    znc_firewall_bypass_port: 6672
    znc_clients:
      - name: limechat
        port: 6667
